# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        OC\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_AMIN, ROLE_ALLOWED_TO_SWITCH ]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main: #Nom arbitraire
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login: 
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /platform
            logout:
                path: fos_user_security_logout
                target: /platform
            remember_me:           #pour eviter que l'utilisateur ait à se connecter à chaque fois
                secret: %secret%

    
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN } #Tout les liens commencant par admin ont besoin du role admin
