services:
    oc_platform.email.application_mailer:
      class: OC\PlatformBundle\Email\ApplicationMailer
      arguments:
        - "@mailer"
    oc_platform.doctrine_listener.application_creation:
      class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
      arguments:
        - "@oc_platform.email.application_mailer"
      tags:
        - {name: doctrine.event_listener, event: postPersist}
    oc_platform.validator.antiflood:
      class: OC\PlatformBundle\Validator\AntifloodValidator
      arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
      tags: 
        - { name: validator.constraint_validator, alias: oc_platform_antiflood}
    oc_platform.beta.html_adder:
      class: OC\PlatformBundle\Beta\BetaHTMLAdder
    oc_platform.beta.listener:
      class: OC\PlatformBundle\Beta\BetaListener
      arguments:
        - "@oc_platform.beta.html_adder"
        - "2018-01-05"
      tags:
        - { name: kernel.event_listener, event: kernel.response, method: processBeta }
    # oc_platform.bigbrother.message_notificator:
    #   class: OC\PlatformBundle\Bigbrother\MessageNotificator
    #   arguments:
    #     - "@mailer"
    # oc_platform.bigbrother.message_listener:
    #   class: OC\PlatformBundle\Bigbrother\MessageListener
    #   arguments:
    #     - "@oc_platform.bigbrother.message_notificator"
    #     - ["alexandre", "marine", "pierre"]
    #   tags:
    #     - { name: kernel.event_listener, event: oc_platform.post_message, method: processMessage }
